### ISSUE TITLE
Dashboard not starting

### ISSUE THREAD

**Issue by Saentist** [dwainscheeren/dwains-lovelace-dashboard#598]
```
Logger: homeassistant.config_entries
Source: custom_components/dwains_dashboard/process_yaml.py:127
Integration: Dwains Dashboard (documentation, issues)
First occurred: 21:36:37  (1 occurrences)
Last logged: 21:36:37 

Error setting up entry for dwains_dashboard
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/dwains_dashboard/__init__.py", line 1570, in async_setup_entry
    process_yaml(hass, config_entry)
  File "/config/custom_components/dwains_dashboard/process_yaml.py", line 127, in process_yaml
    "name": filecontent["name"],
TypeError: 'NoneType' object is not subscriptable

```
What can be a problem
Error come after restart of PC

**Comment by citizenxnz** [comment]
Same problem here

Update: sorry just saw the other issues relating to 2022.7

**Comment by BNoiZe** [comment]
I assume that you are both using Home Assistant 2022.7.0 or higher. DD ist not yet compatible with these versions. See #588

**Comment by Saentist** [comment]
@BNoiZe 
solution there, walking around problem but not solve it.

**Comment by BNoiZe** [comment]
You can call it a solution, but the navigation bar will be missing and you are unable to add/remove entities from the dashboard. HA 2022.7 introduced python 3.10 which broke many integrations. My logs are full of errors related to python now.

**Comment by Saentist** [comment]
That's because is **walking around problem** but not solve it.
As you see also have negatives, as missing nav bar etc.

**Comment by dwainscheeren** [comment]
Try DD 3.2 it was a bug and is now fixed. https://github.com/dwainscheeren/dwains-lovelace-dashboard/releases/tag/v3.2.0

**Comment by Saentist** [comment]
HACS still show 3.1.1 as latest version.

![image](https://user-images.githubusercontent.com/16975883/179845749-bc27a08c-14d3-4347-bf31-b6adcc91584f.png)
